/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package итоговый.проект;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CatTest {
    @Test void appHasAGreeting() {
        Cat classUnderTest = new Cat();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
